volumes:
  mysql:

networks:
  backend:

services:
  mysql:
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
    networks:
      backend:
        aliases:
        - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password2
      - MYSQL_PASSWORD=Password
      - MYSQL_USER=SqlUser
      - MYSQL_DATABASE=sqldb
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 20s
      retries: 2

  backend:
    image: java:1.0
    build: ./java
    networks:
      backend:
        aliases:
        - java
    container_name: java
    ports:
      - 8448:8448
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sqldb
      - SPRING_DATASOURCE_USERNAME=SqlUser
      - SPRING_DATASOURCE_PASSWORD=Password
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "localhost:8448" ]
      interval: 20s
      timeout: 20s
      retries: 2

  frontend:
    image: angular:1.0
    build: ./angular
    environment:
      - BACKEND_URL_ENV_VAR=http://localhost:8448
    ports:
      - 80:80
    depends_on:
      backend:
        service_healthy
    healthcheck:
      test: [ "CMD", "curl", "localhost:80" ]
      interval: 20s
      timeout: 20s
      retries: 2